name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go ${{ vars.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: "${{ vars.GO_VERSION }}"

      - name: Check module dependencies
        shell: bash
        run: |
          go version
          test -z "$(go mod tidy && git status go.* --porcelain)"
          go mod verify
 
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: "${{ vars.GOLANGCI_LINT_VERSION }}"
          only-new-issues: true

  smoke:
    name: Smoke Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go ${{ vars.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: "${{ vars.GO_VERSION }}"

      - name: Run tests
        run: |
          go test -short -timeout 60s ./...

  test:
    name: Test
    needs:
      - lint
      - smoke
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{ fromJSON(vars.GO_VERSIONS) }}
        platform: ${{ fromJSON(vars.PLATFORMS) }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: |
          go test -race -timeout 60s ./...

  build:
    name: Build
    needs:
      - lint
      - smoke
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{ fromJSON(vars.GO_VERSIONS) }}
        platform: ${{ fromJSON(vars.PLATFORMS) }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "${{ vars.GORELEASER_VERSION }}"
          args: build --clean --snapshot --single-target

  coverage:
    name: Coverage
    needs:
      - test
      - build
    if: ${{ github.ref_name == 'main' || github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go ${{vars.GO_VERSION}}
        uses: actions/setup-go@v5
        with:
          go-version: "${{vars.GO_VERSION}}"

      - name: Test
        run: go test -count 1 -coverprofile=coverage.txt ./...

      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          slug: ${{github.repository}}

      - name: Generate Go Report Card
        uses: creekorful/goreportcard-action@v1.0

  devcontainer:
    name: Dev Container
    if: ${{ vars.DEVCONTAINER_IMAGE != '' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Config
        run: |
          cat .devcontainer/devcontainer.json | jq -r '
            {
              DEVCONTAIENR_IMAGE: .image,
              GO_VERSION: .features["ghcr.io/devcontainers/features/go:1"]["version"],
              GOLANGCI_LINT_VERSION: .features["ghcr.io/devcontainers/features/go:1"]["golangciLintVersion"],
              GORELEASER_VERSION: .features["ghcr.io/guiyomh/features/goreleaser:0"]["version"]
            } | to_entries | map("\(.key)=\(.value|tostring)")|.[]' >> "$GITHUB_ENV"

      - name: Check image
        run: test "${{env.DEVCONTAIENR_IMAGE}}" == "${{vars.DEVCONTAIENR_IMAGE}}"
    
      - name: Check go version
        run: test "${{env.GO_VERSION}}" == "${{vars.GO_VERSION}}"

      - name: Check golangci-lint
        run: test "${{env.GOLANGCI_LINT_VERSION}}" == "${{vars.GOLANGCI_LINT_VERSION}}"
        
      - name: Check goreleaser
        run: test "${{env.GORELEASER_VERSION}}" == "${{vars.GORELEASER_VERSION}}"

