name: Release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    name: Release
    uses: grafana/xk6/.github/workflows/tooling-release.yml@zizmor
    permissions:
      contents: write
      packages: write
    with:
      go-version: "1.24.x"
      goreleaser-version: "2.8.2"
