name: Release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    name: Release
    uses: ./.github/workflows/reusable-cli-release.yml
    secrets:
      docker-user: ${{secrets.DOCKERHUB_USERNAME}}
      docker-token: ${{secrets.DOCKERHUB_TOKEN}}
    with:
      go-version: ${{vars.GO_VERSION}}
      goreleaser-version: ${{vars.GORELEASER_VERSION}}
      bats: ./.github/release.bats
