name: Release

on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: write
  packages: write

jobs:
  prerequisites:
    name: Prerequisites
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check vars.GO_VERSION
        run: test -n "${{vars.GO_VERSION}}"

      - name: Check vars.GORELEASER_VERSION
        run: test -n "${{vars.GORELEASER_VERSION}}"

      - name: Check secrets.DOCKERHUB_USERNAME
        run: test -n "${{secrets.DOCKERHUB_USERNAME}}"

      - name: Check secrets.DOCKERHUB_TOKEN
        run: test -n "${{secrets.DOCKERHUB_TOKEN}}"

      - name: Summary
        run: |
          cat >> $GITHUB_STEP_SUMMARY <<END

          ## ${{ github.ref_name }}

          ### Configuration

          Parameter            | Variable           | Value
          ---------------------|--------------------|-----------------------------
          go version for build | GO_VERSION         | ${{vars.GO_VERSION}}
          GoReleaser version   | GORELEASER_VERSION | ${{vars.GORELEASER_VERSION}}

          END


  Release:
    needs: ["prerequisites"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go ${{ vars.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: "${{ vars.GO_VERSION }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'amd64,arm64'

      - name: Setup Bats
        if: ${{ hashFiles('.github/release.bats') != '' }}
        run: sudo apt-get install -y bats

      - name: GoReleaser snapshot
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "${{ vars.GORELEASER_VERSION }}"
          args: release --clean --snapshot

      - name: Test Snapshot
        if: ${{ hashFiles('.github/release.bats') != '' }}
        run: bats .github/release.bats

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}          

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: GoReleaser release
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "${{ vars.GORELEASER_VERSION }}"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
