name: Validate

env:
  GO_VERSIONS: '["1.23.x", "1.22.x"]'
  PLATFORMS: '["ubuntu-latest", "windows-latest", "macos-latest"]'

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  config:
    name: Config
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{steps.go-version.outputs.version}}
      go-versions: ${{steps.go-versions.outputs.versions}}
      platforms: ${{steps.platforms.outputs.platforms}}
      golangci-lint-version: ${{steps.golangci-lint-version.outputs.version}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Retrieve go version
        id: go-version
        shell: bash
        run: echo "version=$(echo '${{env.GO_VERSIONS}}' | jq -r '.[0]')" >> $GITHUB_OUTPUT
      - name: Retrieve go versions
        id: go-versions
        shell: bash
        run: |
          cat >> $GITHUB_OUTPUT <<END
          versions=${{env.GO_VERSIONS}}
          END
      - name: Retrieve go versions
        id: platforms
        shell: bash
        run: |
          cat >> $GITHUB_OUTPUT <<END
          versions=${{env.GO_VERSIONS}}
          END
      - name: Retrieve golangci-lint version
        id: golangci-lint-version
        run: |
          echo "version=$(head -n 1 .golangci.yml | tr -d '# ')" >> $GITHUB_OUTPUT

  lint:
    name: Lint
    needs: ["config"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go ${{ needs.config.outputs.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ needs.config.outputs.go-version }}

      - name: Check module dependencies
        shell: bash
        run: |
          go version
          test -z "$(go mod tidy && git status go.* --porcelain)"
          go mod verify

 
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ needs.config.outputs.golangci-lint-version }}
          only-new-issues: true

  trial:
    name: Trial
    runs-on: ubuntu-latest
    needs: ["config"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go ${{ needs.config.outputs.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ needs.config.outputs.go-version }}

      - name: Run tests
        run: |
          go test -short -timeout 60s ./...

  test:
    name: Test
    needs:
      - config
      - lint
      - trial
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{ fromJSON(needs.config.outputs.go-versions) }}
        platform: ${{ fromJSON(needs.config.outputs.platforms) }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: |
          go test -race -timeout 60s ./...

  build:
    name: Build
    needs:
      - config
      - lint
      - trial
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{ fromJSON(needs.config.outputs.go-versions) }}
        platform: ${{ fromJSON(needs.config.outputs.platforms) }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "2.6.1"
          args: build --clean --snapshot --single-target

  coverage:
    name: Coverage
    needs:
      - config
      - test
      - build
    if: ${{ github.ref_name == 'main' || github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go ${{needs.config.outputs.go-version}}
        uses: actions/setup-go@v5
        with:
          go-version: ${{needs.config.outputs.go-version}}

      - name: Test
        run: go test -count 1 -coverprofile=coverage.txt ./...

      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          slug: ${{github.repository}}

      - name: Generate Go Report Card
        uses: creekorful/goreportcard-action@v1.0

